name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to production
    uses: mnhn-mosaic/github-actions/.github/workflows/deploy-project.yml@main
    secrets: inherit
    with:
      environment: production
      host: 172.20.22.27
      stack: changing-natures-api
      repository: changing-natures-api
      branch: main
